### PR TITLE
[core/erc20s] fix handling of confliciting erc20 symbols

### PR DESCRIPTION
**Pull request by zviadm**
* plus update default token list for OpticsV2 support

### CODE REVIEW

**Comment by Unkwncrypto** [comment]
> * plus update default token list for OpticsV2 support

Not working on my end

**Comment by zviadm** [comment]
> > * plus update default token list for OpticsV2 support
> 
> Not working on my end

What is the part that is not working? If you have Celo Terminal v1.11.8 or later, you should have access to Optics V2 tokens like USDC or DAI

**Comment by Unkwncrypto** [comment]
All my accounts are frozen or changed

**Comment by Unkwncrypto** [comment]
Accounts closing old accounts need to been updated and recovered data and networking wise to . These transactions and locks or holds ain’t paying they just keep getting burnt gas’s to high and won’t except what it ask for . I know what it is just don’t got the proper tools .

**Pull request merged**
